- from: https://auth.internal.cdssandbox.xyz
  to: http://auth.internal.local:8000
  allowed_domains:
    - internal.cdssandbox.xyz
  cors_allow_preflight: true
  timeout: 30s
- from: https://httpd.internal.cdssandbox.xyz
  to: http://httpd.internal.local
  allowed_domains:
    - cds-snc.ca